### ISSUE TITLE
Multiple Panels on the same side

### ISSUE THREAD

**Issue by hongc-cc** [scotch-io/scotch-panels#13]
Awesome work.
Is that possible to make multiple panels on the same side of a div?
With this function, we can build even a multilevel off canvas navigation

example:
http://codyhouse.co/demo/side-team-member-bio/

**Comment by YuriCurtis** [comment]
Hey Nick!

I used your Off-Canvas tutorial and got the toggle working fine. I wanted to not only update to using the Scotch Panels plug-in but also implement the multiple panels on one side since ideally I want to be able to swap the stacking order just like the multiple panels and I am hoping you can give me some guidance regarding how to target the classes/id's properly. My issue is trying to translate the class names (site-wrapper, site-canvas, site-menu) from the tutorial to using the plug-in.

This is the site as it stands: [My Site](http://art.yuricurtis.com/broken.html)

Thanks
